"""nullable changes to name, email fields

Revision ID: b42770646c43
Revises: c4e64f78e37b
Create Date: 2026-08-26 19:23:48.652995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42770646c43'
down_revision: Union[str, Sequence[str], None] = 'c4e64f78e37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('leads', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
